wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.10.6
    start_time: 1691340486.779954
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      3:
      - 13
      - 16
      - 23
      4: 3.10.6
      5: 0.13.4
      8:
      - 2
      - 5
epochs:
  desc: null
  value: 500
max_learning_rate:
  desc: null
  value: 0.006
