BinarySegmentation:
  


MultiClassSegmentation:

  batch_size: 2
  num_classes: 3
  colors: [ [  0,   0,   0],[0,255,0],[0,0,255]]
  label_colours: {0: [0, 0, 0], 1: [0, 255, 0], 2: [0, 0, 255]}
  valid_classes: [0,85,170]
  class_names: ["Background","Pupil","Iris"]
  class_map: {0: 0, 85: 1, 170: 2}
  train_img_path: /home/nipun/Documents/Uni_Malta/Datasets/Datasets/Miche/MICHE_MULTICLASS/Shorter_Dataset/train_img/
  train_mask_path: /home/nipun/Documents/Uni_Malta/Datasets/Datasets/Miche/MICHE_MULTICLASS/Shorter_Dataset/train_masks/
  val_img_path: /home/nipun/Documents/Uni_Malta/Datasets/Datasets/Miche/MICHE_MULTICLASS/Shorter_Dataset/val_img
  val_mask_path: /home/nipun/Documents/Uni_Malta/Datasets/Datasets/Miche/MICHE_MULTICLASS/Shorter_Dataset/val_masks/
  max_lr: 1e-3
  model_name: efficientnet-b3
  experiment_name: Short_Experiment
  num_epochs: 10
  weight_decay: 1e-6
  resize_amt: 512
  




